export type ApiUserProfile = {
  id?: string;
  userId?: string;
  avatar?: string | null;
  dateOfBirth?: string | null;
  identificationNumber?: string | null;
  identificationType?: string | null;
  identificationDocument?: string | null;
  businessName?: string | null;
  taxId?: string | null;
  isVerified?: boolean;
  verifiedAt?: string | null;
  isSeller?: boolean;
  sellerStatus?: string | null;
  sellerVerifiedAt?: string | null;
  sellerRejectedReason?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  createdAt?: string;
  updatedAt?: string;
};

export type ApiUser = {
  id: string;
  email: string;
  emailVerified?: boolean;
  fullName?: string | null;
  phone?: string | null;
  role?: string;
  isActive?: boolean;
  isSuspended?: boolean;
  googleId?: string | null;
  appleId?: string | null;
  isDeleted?: boolean;
  suspensionReason?: string | null;
  suspensionUntil?: string | null;
  walletBalance?: number;
  currency?: string;
  payoutPinSet?: boolean;
  language?: string;
  timezone?: string | null;
  notificationPreferences?: string | null;
  lastLoginAt?: string | null;
  createdAt?: string;
  updatedAt?: string;
  online?: boolean;
  profile?: ApiUserProfile | null;
};

export type ApiOrderUser = {
  id?: string;
  email?: string;
  fullName?: string | null;
  profile?: {
    firstName?: string | null;
    lastName?: string | null;
  } | null;
};

export type ApiOrderVehicleSnapshot = {
  id?: string;
  vin?: string;
  slug?: string | null;
  make?: string;
  model?: string;
  year?: number;
  priceUsd?: number | null;
  mileage?: number | null;
  vehicleType?: string | null;
  transmission?: string | null;
  fuelType?: string | null;
  engineSize?: string | null;
  drivetrain?: string | null;
  dealerName?: string | null;
  dealerState?: string | null;
  dealerCity?: string | null;
  dealerZipCode?: string | null;
  images?: string[] | null;
  status?: string | null;
  apiListingId?: string;
};

export type ApiOrder = {
  id: string;
  requestNumber?: string | null;
  status?: string;
  previousStatus?: string[] | null;
  createdAt?: string;
  updatedAt?: string;
  statusChangedAt?: string | null;
  statusChangedBy?: string | null;
  userId?: string;
  user?: ApiOrderUser | null;
  vehicleId?: string | null;
  vehicle?: ApiOrderVehicleSnapshot | null;
  vehicleSource?: string | null;
  externalVehicleId?: string | null;
  externalProvider?: string | null;
  vehicleSnapshot?: ApiOrderVehicleSnapshot | null;
  destinationCountry?: string | null;
  destinationState?: string | null;
  destinationCity?: string | null;
  destinationAddress?: string | null;
  destinationPort?: string | null;
  originPort?: string | null;
  customerNotes?: string | null;
  specialRequests?: string | null;
  deliveryInstructions?: string | null;
  estimatedDeliveryDate?: string | null;
  actualDeliveryDate?: string | null;
  paymentBreakdown?: {
    totalUsd?: number;
    totalUsedDeposit?: number | null;
    shippingMethod?: string | null;
    breakdown?: Record<string, number | string | null> | null;
  } | null;
  quotedPriceUsd?: number | null;
  depositAmountUsd?: number | null;
  totalLandedCostUsd?: number | null;
  totalLandedCostLocal?: number | null;
  localCurrency?: string | null;
  exchangeRate?: number | null;
  exchangeRateDate?: string | null;
  quoteExpiresAt?: string | null;
  shippingMethod?: string | null;
  paymentMethod?: string | null;
  priority?: string | null;
  refundRequested?: boolean | null;
  refundApproved?: boolean | null;
  refundAmount?: number | null;
  cancelledAt?: string | null;
  cancelledBy?: string | null;
  cancellationReason?: string | null;
  tags?: string[] | null;
  payments?: ApiPayment[] | null;
};

export type ApiPayment = {
  id: string;
  orderId?: string;
  userId?: string;
  amountUsd?: number | null;
  amountLocal?: number | null;
  localCurrency?: string | null;
  exchangeRate?: number | null;
  paymentType?: string | null;
  paymentMethod?: string | null;
  paymentProvider?: string | null;
  status?: string | null;
  escrowStatus?: string | null;
  transactionRef?: string | null;
  providerTransactionId?: string | null;
  receiptUrl?: string | null;
  evidenceUrls?: string[] | null;
  evidencePublicIds?: string[] | null;
  evidenceUploadedAt?: string | null;
  adminConfirmedBy?: string | null;
  adminConfirmedAt?: string | null;
  adminNote?: string | null;
  refundAmount?: number | null;
  refundReason?: string | null;
  refundedAt?: string | null;
  refundedBy?: string | null;
  description?: string | null;
  metadata?: {
    calculation?: {
      paymentAmount?: number | null;
    } | null;
  } | null;
  createdAt?: string;
  updatedAt?: string;
  completedAt?: string | null;
  order?: ApiOrder | null;
  user?: ApiOrderUser | null;
};
